<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for system_themes_admin_form.
 *
 * @see admin_theme_form_system_themes_form_alter_submit()
 */
function admin_theme_form_system_themes_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $paths = \Drupal::configFactory()->getEditable('admin_theme.settings')->get('paths');
  $form['admin_theme']['admin_theme_paths'] = array(
    '#type' => 'textarea',
    '#title' => t('Pages'),
    '#default_value' => $paths,
    '#description' => t("Specify pages by using their paths. Enter one path per line. The '*' character is a wildcard. Example paths are %user for the current user's page and %user-wildcard for every user page. %front is the front page.", array(
      '%user' => '/user',
      '%user-wildcard' => '/user/*',
      '%front' => '<front>',
    )),
  );
  $form['#submit'][] = 'admin_theme_form_system_themes_form_alter_submit';
}

/**
 * Form submission handler for system_themes_admin_form.
 *
 * @see admin_theme_form_system_themes_admin_form_alter()
 */
function admin_theme_form_system_themes_form_alter_submit($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('admin_theme.settings')
    ->set('paths', $form_state->getValue('admin_theme_paths'))
    ->save();
  \Drupal::service('router.builder')->setRebuildNeeded();
}
